# Importing the dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importinh dataset and Preprocessing

In [2]:
dataset = pd.read_csv("creditcard.csv")
dataset.head(3)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89220 entries, 0 to 89219
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    89220 non-null  int64
 1   V1      89220 non-null  float64
 2   V2      89220 non-null  float64
 3   V3      89220 non-null  float64
 4   V4      89220 non-null  float64
 5   V5      89220 non-null  float64
 6   V6      89220 non-null  float64
 7   V7      89220 non-null  float64
 8   V8      89220 non-null  float64
 9   V9      89219 non-null  float64
 10  V10     89219 non-null  float64
 11  V11     89219 non-null  float64
 12  V12     89219 non-null  float64
 13  V13     89219 non-null  float64
 14  V14     89219 non-null  float64
 15  V15     89219 non-null  float64
 16  V16     89219 non-null  float64
 17  V17     89219 non-null  float64
 18  V18     89219 non-null  float64
 19  V19     89219 non-null  float64
 20  V20     89219 non-null  float64
 21  V21     89219 non-null  float64
 22  V22     89219 non-null  float64
 23  V23     89219 non-null  float64
 24  V24     89219 non-null  float64
 25  V25     89219 non-null  float64
 26  V26     89219 non-null  float64
 27  V27     89219 non-null  float64
 28  V28     89219 non-null  float64
 29  Amount  89219 non-null  float64
 30  Class   89219 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 21.1 MB

In [4]:
dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [5]:
dataset.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,89220.000000,89220.000000,89220.000000,89220.000000,89220.000000,89220.000000,89220.000000,89220.000000,89220.000000,89219.000000,...,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000,89219.000000
mean,39715.015501,-0.265000,-0.039318,0.678729,0.162808,-0.278291,0.094282,-0.109561,0.054698,-0.028905,...,-0.029895,-0.106761,-0.037413,0.009718,0.132571,0.027095,0.001317,0.002412,98.532339,0.002365
std,16026.485819,1.873458,1.662182,1.352995,1.359523,1.370149,1.302130,1.230881,1.215535,1.129755,...,0.727551,0.634882,0.625389,0.594412,0.441100,0.496667,0.389659,0.326436,266.941369,0.048574
min,0.000000,-56.407510,-72.715728,-33.680984,-5.172595,-42.147898,-26.160506,-31.764946,-73.216718,-9.283925,...,-34.830382,-10.933144,-26.751119,-2.836627,-7.495741,-2.534330,-9.390980,-9.617915,0.000000,0.000000
25%,32165.000000,-1.028772,-0.603310,0.182821,-0.719037,-0.897378,-0.646335,-0.601120,-0.139866,-0.692643,...,-0.223859,-0.526395,-0.177767,-0.322006,-0.131948,-0.325915,-0.063273,-0.005744,7.675000,0.000000
50%,42017.000000,-0.262209,0.071676,0.760383,0.185833,-0.313066,-0.156213,-0.070878,0.071465,-0.102804,...,-0.057810,-0.082239,-0.049619,0.064928,0.171090,-0.070776,0.009396,0.023123,26.990000,0.000000
75%,52274.250000,1.152744,0.727352,1.386516,1.037554,0.254270,0.488962,0.416670,0.355072,0.589973,...,0.118714,0.309107,0.081203,0.406088,0.420191,0.306496,0.082733,0.076409,89.950000,0.000000
max,62480.000000,1.960497,18.902453,4.226108,16.715537,34.801666,22.529298,36.677268,20.007208,10.392889,...,22.614889,10.503090,18.946734,4.014444,5.525093,3.517346,12.152401,33.847808,19656.530000,1.000000

In [6]:
dataset.shape

(89220, 31)

In [7]:
dataset['Class'].value_counts()

Class
0.0    89008
1.0      211
Name: count, dtype: int64

0 --> Normal transaction

1 --> Fraud transaction

In [8]:
# seperating the data for analysis
legit = dataset[dataset.Class == 0]
fraud = dataset[dataset.Class == 1]

In [10]:
legit.shape, fraud.shape

((89008, 31), (211, 31))

# Under Sampling

Build a sample dataset containing similar distribution of normal and fraud data point

we take 492 random data from the legit dataset and combine them with the fraud dataset

In [15]:
# select random 492 datapoints
legit_sample = legit.sample(n=211)

### Concatenting the datasets

In [16]:
df = pd.concat([legit_sample, fraud], axis=0)

In [17]:
df.head(3)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
70011,53670,1.285602,0.210040,-0.329152,0.817121,0.352866,-0.163912,0.205316,-0.132580,0.125101,...,-0.050435,-0.173679,-0.294032,-1.011955,0.852384,-0.243651,0.004167,0.010602,33.89,0.0
64810,51317,-2.627401,0.572981,-0.663697,-0.654239,2.541953,3.319674,-0.349112,1.445454,-0.220723,...,-0.127349,-0.570716,-0.819298,1.039775,0.835466,-0.482289,-0.550711,-0.408219,1.00,0.0
44758,42072,-0.983182,1.464708,0.380228,0.015465,0.690238,-0.081966,0.433720,0.756757,-0.838013,...,0.166568,0.311162,-0.180559,-0.472954,-0.068384,-0.487631,0.020550,0.083385,1.00,0.0

In [18]:
df.shape

(422, 31)

In [19]:
df['Class'].value_counts()

Class
0.0    211
1.0    211
Name: count, dtype: int64

# Spliting the dataset into input and output data

In [21]:
x = df.iloc[:,:-1]
y = df['Class']

# Spliting into training and testing data

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

# Model training

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [24]:
lr.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluation

In [25]:
lr.score(x_train, y_train)

0.9614243323442137

In [27]:
lr.score(x_test, y_test)

0.9411764705882353

### Making a predictive system

In [34]:
input = (x_test.iloc[[63]])

# Convert the input data into a numpy array
input_array = np.asarray(input)

# Reshaping the numpy array as we predict for only one instance
input_reshaped = input_array.reshape(1,-1)

prediction = lr.predict(input_reshaped)
print(prediction)

if(prediction[0] == 0):
    print("Normal Transaction")
else:
    print("Fraud Transaction")

[1.]
Fraud Transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [35]:
print(y_test.iloc[[63]])

68320    1.0
Name: Class, dtype: float64