# Importing the dependecies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# importing the dataset
df = pd.read_csv("Fake_news.csv", engine='python', on_bad_lines='skip')
df.head(3)

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1

In [4]:
df.shape

(2470, 4)



*  0 -> Fake
*  1 -> Real

In [5]:
import re                           # use to help to read text data from the document
from nltk.corpus import stopwords       # important content of the text
from nltk.stem.porter import PorterStemmer   # it removes the prefix and sufix from the root word
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
#  printing the stopwords in english
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

# Data PreProcessing

In [8]:
df.isnull().sum()

Unnamed: 0     0
title         26
text          13
label         15
dtype: int64

In [9]:
# replaceing missing values with Null string
df = df.fillna('')

In [10]:
# Combining the title and text into one single column
df['content'] = df['title']+' '+df['text']

In [11]:
df.head(5)

,Unnamed: 0,title,text,label,content
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1,1,,Did they post their votes for Hillary already?,1,Did they post their votes for Hillary already?
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,SATAN 2: Russia unvelis an image of its terrif...

In [13]:
# Spliting data into input and output data
x = df.drop(columns='label', axis=1)
y = df['label']

Steaming:

steaming is not but the process of reduceing the word to its root word.

example:
actor, acting,etc ---> act

In [12]:
porter_steam = PorterStemmer()

In [13]:
def steaming (content):
  steamed_content = re.sub('[^a-zA-Z]',' ',content)
  steamed_content = steamed_content.lower()
  steamed_content = steamed_content.split()
  steamed_content = [porter_steam.stem(word) for word in steamed_content if not word in stopwords.words('english')]
  steamed_content = ' '.join(steamed_content)
  return steamed_content

In [ ]:
# Apply steaming to all the content columns
df['content'] = df['content'].apply(steaming)

In [ ]:
print(df['content'])

In [14]:
# seperating data and levels
x = df['content'].values
y = df['label'].values

In [15]:
# converting the textual data into numerical data using vectorization
vectorizer = TfidfVectorizer()
vectorizer.fit(x)

x = vectorizer.transform(x)

In [16]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 634256 stored elements and shape (2470, 45073)>
  Coords	Values
  (0, 0)	0.03082721099143332
  (0, 102)	0.016674192549905226
  (0, 155)	0.04474714246191952
  (0, 158)	0.03402273784956573
  (0, 978)	0.02783832420817534
  (0, 1117)	0.030202627849190887
  (0, 1627)	0.008521772954793855
  (0, 1768)	0.028817570263096663
  (0, 1886)	0.01741495025266656
  (0, 2189)	0.04474714246191952
  (0, 2207)	0.015961561640112084
  (0, 2208)	0.011671822191299102
  (0, 2313)	0.07421384492233966
  (0, 2331)	0.03328681246079499
  (0, 2459)	0.02929711204110109
  (0, 2530)	0.009584668184611433
  (0, 2541)	0.02679094568848963
  (0, 2622)	0.023411971361196146
  (0, 2636)	0.04731525408133938
  (0, 2697)	0.019124292765351818
  (0, 2758)	0.014006243930997208
  (0, 2759)	0.026121557579523908
  (0, 2847)	0.00766066754514366
  (0, 2900)	0.12925932501293852
  (0, 3050)	0.013821835338144952
  :	:
  (2469, 37178)	0.04279179846787341
  (2469, 37961)	0.07457838544969493
  (2469, 38129)	0.04153673695160365
  (2469, 38660)	0.21887227121590772
  (2469, 38665)	0.06502040234370679
  (2469, 38797)	0.016015611834530343
  (2469, 39080)	0.07432948633933766
  (2469, 39727)	0.02131465223171924
  (2469, 39856)	0.06265520854683086
  (2469, 40202)	0.07560394012094149
  (2469, 40316)	0.04354365260372321
  (2469, 40483)	0.07672730816196588
  (2469, 40770)	0.020699386362015296
  (2469, 40868)	0.05523428855461558
  (2469, 41103)	0.03397783016029024
  (2469, 41484)	0.047637192694607464
  (2469, 41587)	0.08752711702380556
  (2469, 41855)	0.015812508990192455
  (2469, 41882)	0.03462205844675684
  (2469, 41952)	0.05697121181103839
  (2469, 42200)	0.025123081438543447
  (2469, 42508)	0.04315664567389501
  (2469, 42699)	0.0711876369815724
  (2469, 43004)	0.022031877514273695
  (2469, 43230)	0.05685066232259022

In [17]:
print(y)

['1' '1' '1' ... '1' '0' '1']

# Spliting the data into train and test data

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Modeling training

In [22]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

Model Evaluation

In [23]:
lr.score(x_test, y_test)

0.9068825910931174

In [24]:
lr.score(x_train, y_train)

0.965080971659919

# Making a Predictive system

In [27]:
X_new = x_test[111]

prediction = lr.predict(X_new)
print(prediction)

if (prediction[0]==0):
  print('The news is Fake')
else:
  print('The news is Real')

['1']
The news is Real

In [28]:
print(y_test[111])

1