# Importing the dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data collection and Analysis

In [2]:
dataset = pd.read_csv("/content/spam_ham_dataset.csv")
dataset.head(3)

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0

In [3]:
dataset.shape

(5171, 4)

In [4]:
dataset.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

spam --> 1

ham --> 0

In [5]:
# seperating the data as texts and label
x = dataset['text']
y = dataset['label_num']

In [6]:
x.head(5)

0    Subject: enron methanol ; meter # : 988291\r\n...
1    Subject: hpl nom for january 9 , 2001\r\n( see...
2    Subject: neon retreat\r\nho ho ho , we ' re ar...
3    Subject: photoshop , windows , office . cheap ...
4    Subject: re : indian springs\r\nthis deal is t...
Name: text, dtype: object

In [7]:
y.head(5)

0    0
1    0
2    0
3    1
4    0
Name: label_num, dtype: int64

# Spliting the dataset into training and testing

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4136,), (1035,), (4136,), (1035,))

Feature Extraction

In [11]:
# transform the text data to feature vector so that can be used as input to the logistic regression model
from sklearn.feature_extraction.text import TfidfVectorizer
feature_extraction = TfidfVectorizer(min_df=1, stop_words = "english", lowercase=True)

x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)

# convsert y_train and y_test values as integers
y_train = y_train.astype('int')
y_test = y_test.astype('int')
#

In [13]:
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 272247 stored elements and shape (4136, 44934)>
  Coords	Values
  (0, 38949)	0.017878875876381765
  (0, 6195)	0.20656873875758883
  (0, 4614)	0.16294956018571463
  (0, 39249)	0.12748535284831222
  (0, 38525)	0.09159408089861229
  (0, 11771)	0.23670472985304958
  (0, 13791)	0.16294956018571463
  (0, 6747)	0.09903210769960345
  (0, 39246)	0.4313736004117896
  (0, 15708)	0.1319785723174904
  (0, 12851)	0.09682668459944212
  (0, 4613)	0.10037476430043707
  (0, 11914)	0.08981741277377701
  (0, 39786)	0.11233661957212557
  (0, 36719)	0.09831745403603642
  (0, 34224)	0.1347346131883818
  (0, 15706)	0.3768048757997831
  (0, 33825)	0.11412599930494485
  (0, 34960)	0.08479519389064367
  (0, 28509)	0.22555561160019436
  (0, 18148)	0.07880553005199499
  (0, 29857)	0.07841824683974766
  (0, 34215)	0.10994922837779132
  (0, 16782)	0.07603085564541341
  (0, 13837)	0.054684864025571434
  :	:
  (4135, 40596)	0.08127240147767889
  (4135, 5138)	0.32996496905585093
  (4135, 25483)	0.17642060560095965
  (4135, 10147)	0.08061259583927156
  (4135, 24525)	0.20986367485421245
  (4135, 0)	0.2527704280184989
  (4135, 32291)	0.09124412794447356
  (4135, 761)	0.06432867811359633
  (4135, 70)	0.05786352830846692
  (4135, 50)	0.05134205755491043
  (4135, 29855)	0.06340566376528484
  (4135, 26204)	0.06836772238796647
  (4135, 16739)	0.07219222161962699
  (4135, 13745)	0.1362899929286617
  (4135, 476)	0.06655109210826014
  (4135, 18018)	0.1088083650049757
  (4135, 18701)	0.08608709991653135
  (4135, 1645)	0.08267258217414963
  (4135, 41940)	0.07805903846232892
  (4135, 35386)	0.07397265619989253
  (4135, 974)	0.08631055854188856
  (4135, 32466)	0.08543352034440876
  (4135, 44404)	0.13752815300743584
  (4135, 648)	0.5501126120297434
  (4135, 3280)	0.28502034903568646

# Model Training

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [15]:
model.fit(x_train_features, y_train)

LogisticRegression()

# Evaluating the model

In [16]:
model.score(x_train_features, y_train)

0.9961315280464217

In [17]:
model.score(x_test_features, y_test)

0.9893719806763285

# Build a Predictive System

In [22]:
input = ["re : tenaska iv 10 / 00 we have received all of the money from the spot sales for tenaska iv in october 2000 , except for the tenaska iv sale and the $ 0 . 04 fee . megan"]

# convert text to features vector
input_features = feature_extraction.transform(input)

# making prediction
prediction = model.predict(input_features)
print(prediction)

if prediction[0] == 0:
  print("Ham mail")
else:
  print("Spam mail")

[0]
Ham mail